version: "3.8"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4650
    ports:
      - 5432:5432
    volumes: 
      - dbdata:/var/lib/postgresql/data

  web:
    build: ./
    depends_on:
      - "database"
    ports:
      - 8080:8080
volumes:
  dbdata:  